import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import { auth } from "../auth"
import { Login } from "@/components/Login";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth()

  /*   if (!session?.user) return null  */

  return (

    <html lang="en">
      <body className={inter.className}>

        {/*  {!authSession?.user && (
          <Link className="font-medium mt-2 text-blue-600 hover:underline" href="/login">
            Login
          </Link>
        )}
        <NavBar />
        {authSession?.user && 
        <UserInfo user={authSession.user} />
        } */
          session?.user ? <NavBar /> : null}
        <div className="flex items-center justify-center py-20">
          {session?.user ? children : <Login />}

        </div>
        <Footer />
      </body>
    </html>

  );
}
