import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import { SessionProvider } from "next-auth/react";
import SessionWrapper from "@/components/SessionWrapper";
import { getServerAuthSession } from "@/actions/auth";
import UserInfo from "@/components/UserInfo";
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  /*   const useStore = create((set) => ({
      cartCount: 0,
      increaseCartCount: () => set((state: any) => ({ cartCount: state.cartCount + 1 }))
    })) */
  //const cartCount = useCart(state=>state.cartCount)
  //const session = await getServerSession(authOptions)
  /*   console.log(session?.user)
    if(session){
      return (
        <SessionWrapper>
          <html lang="en">
            <body className={inter.className}>
              <NavBar />
    
              <div>SESSION VAR</div>
              <Footer />
            </body>
          </html>
        </SessionWrapper>
      )
    } */
  /*   const authSession = await getServerAuthSession(); */

  return (
      <html lang="en">
        <body className={inter.className}>

          {/*  {!authSession?.user && (
          <Link className="font-medium mt-2 text-blue-600 hover:underline" href="/login">
            Login
          </Link>
        )} */}
          <NavBar />
          {/*  {authSession?.user && 
        <UserInfo user={authSession.user} />
        } */}
          <div className="flex items-center justify-center py-20">
            {children}
          </div>
          <Footer />
        </body>
      </html>
  );
}
